using Models;

namespace Helpers {
    public static class Converter {
        public static Lead Convert(ZendeskSell.Leads.LeadResponse leadResponse) =>
            new Lead() {
                ID = leadResponse.ID,
                Link = leadResponse.GetLink(),
                CreatorID = leadResponse.CreatorID,
                OwnerID = leadResponse.OwnerID,
                FirstName = leadResponse.FirstName,
                LastName = leadResponse.LastName,
                OrganizationName = leadResponse.OrganizationName,
                Status = leadResponse.Status,
                SourceID = leadResponse.SourceID,
                Title = leadResponse.Title,
                Description = leadResponse.Description,
                Industry = leadResponse.Industry,
                Website = leadResponse.Website,
                Email = leadResponse.Email,
                Phone = leadResponse.Phone,
                Mobile = leadResponse.Mobile,
                Fax = leadResponse.Fax,
                Twitter = leadResponse.Twitter,
                Facebook = leadResponse.Facebook,
                LinkedIn = leadResponse.LinkedIn,
                Skype = leadResponse.Skype,
                Address = new Address(leadResponse.Address),
                CreatedAt = leadResponse.CreatedAt.ToString(),
                UpdatedAt = leadResponse.UpdatedAt.ToString(),
                Tags = leadResponse.Tags,
                CustomFields = leadResponse.CustomFields,
            };

        public static Contact Convert(ZendeskSell.Contacts.ContactResponse contactResponse) =>
            new Contact() {
                ID = contactResponse.ID,
                Link = contactResponse.GetLink(),
                CreatorID = contactResponse.CreatorID,
                OwnerID = contactResponse.OwnerID,
                Name = contactResponse.Name,
                FirstName = contactResponse.FirstName,
                LastName = contactResponse.LastName,
                IsOrganization = contactResponse.IsOrganization,
                ContactID = contactResponse.ContactID,
                ParentOrganizationID = contactResponse.ParentOrganizationID,
                CustomerStatus = contactResponse.CustomerStatus,
                ProspectStatus = contactResponse.ProspectStatus,
                Title = contactResponse.Title,
                Description = contactResponse.Description,
                Industry = contactResponse.Industry,
                Website = contactResponse.Website,
                Email = contactResponse.Email,
                Phone = contactResponse.Phone,
                Mobile = contactResponse.Mobile,
                Fax = contactResponse.Fax,
                Twitter = contactResponse.Twitter,
                Facebook = contactResponse.Facebook,
                Linkedin = contactResponse.Linkedin,
                Skype = contactResponse.Skype,
                Address = new Address(contactResponse.Address),
                BillingAddress = new Address(contactResponse.BillingAddress),
                ShippingAddress = new Address(contactResponse.ShippingAddress),
                CreatedAt = contactResponse.CreatedAt.ToString(),
                UpdatedAt = contactResponse.UpdatedAt.ToString(),
                Tags = contactResponse.Tags,
                CustomFields = contactResponse.CustomFields
            };

        public static Deal Convert(ZendeskSell.Deals.DealResponse dealResponse) =>
            new Deal() {
                ID = dealResponse.ID,
                Link = dealResponse.GetLink(),
                CreatorID = dealResponse.CreatorID,
                OwnerID = dealResponse.OwnerID,
                LastActivityAt = dealResponse.LastActivityAt.ToString(),
                LastStageChangeByID = dealResponse.LastStageChangeByID,
                DropboxEmail = dealResponse.DropboxEmail,
                OrganizationID = dealResponse.OrganizationID,
                Name = dealResponse.Name,
                Value = dealResponse.Value,
                ContactID = dealResponse.ContactID,
                Currency = dealResponse.Currency,
                Hot = dealResponse.Hot,
                StageID = dealResponse.StageID,
                LastStageChangeAt = dealResponse.LastStageChangeAt.ToString(),
                AddedAt = dealResponse.AddedAt.ToString(),
                SourceID = dealResponse.SourceID,
                LossReasonID = dealResponse.LossReasonID,
                UnqualifiedReasonID = dealResponse.UnqualifiedReasonID,
                EstimatedCloseDate = dealResponse.EstimatedCloseDate.ToString(),
                CustomizedWinLikelihood = dealResponse.CustomizedWinLikelihood,
                CreatedAt = dealResponse.CreatedAt.ToString(),
                UpdatedAt = dealResponse.UpdatedAt.ToString(),
                Tags = dealResponse.Tags,
                CustomFields = dealResponse.CustomFields,
            };
    }
}
